version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'ci'
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
